### ISSUE TITLE
Support of int8 (bigint)

### ISSUE THREAD

**Issue by PedroMartinhoDias** [jeromew/node-pg-copy-streams-binary#13]
Hi,

I have the need to use bigint type (int8). Is it possible to have it in a new version?
I saw that on pg_types there is for int2 and int4, so it would be the case to write methods for int8 and apply word64be.

I presume that it would work for array aswell.

Many thanks for the library.

**Comment by jeromew** [comment]
Hello,
thanks for the report.

In order to support a new type, we need to agree on how the datatype will be implemented in javascript.

what is your use case and how to you intend to manipulate the int8 datas in javascript ?

**Comment by PedroMartinhoDias** [comment]
Hi Jerome, sorry for the late reply and thanks for coming back to me on this.

My real intent is to expand the supported datatypes by this library, them being, bigint(int8), uuid and inet. I could live with the last one's in text type, but for the first one, int8, it would be very useful. For implementation is relatively strait forward. Based on int4 implementation, we would have to use word64be instead. For the implementation of uuid and inet, I'm not sure yet how to do that.

Do you think is possible if I submit a PR and you can check if it can go to a new version?

Many thanks,
Pedro

**Comment by PedroMartinhoDias** [comment]
// int8
const int8send = function (buf, value) {
  buf.word64be(value)
}
const int8recv = function (buf) {
  return buf.readInt64BE(0)
}

**Comment by jeromew** [comment]
sorry I did not see your replies (I was away from my computer).
I added comments on your PR code because I dont understand where readInt64BE comes from.

We could use the new BigInt type that seem to have appeared since node 10.4 - https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/BigInt

**Comment by jeromew** [comment]
int8 support is now available in 2.2.0
