### ISSUE TITLE
No way to use with literal array

### ISSUE THREAD

**Issue by gajus** [jeromew/node-pg-copy-streams-binary#2]
Looking at the documentation/ code, there appears to be no clean way to use this library with literal array input.

I already have an array of values and I want to construct a binary stream to write those variables to the database.

The blocker is that `mapping` is required and it will attempt to decode the input, i.e. I cannot just do:

```js
const copyFromStream = finalConnection.query(from(finalSql));

const transformStream = pgCopyTransform({
  targets: [
    copyFromStream,
  ],
});

transformStream.push([
  0,
  {
    type: 'int4',
    value: 1,
  },
  {
    type: 'int4',
    value: 1,
  },
  {
    type: 'int4',
    value: 1,
  },
  {
    type: 'int4',
    value: 1,
  },
  {
    type: 'int4',
    value: 1,
  },
]);

```

**Comment by gajus** [comment]
Never mind. Just realised that I can use `deparser` directly.

```js
const copyFromStream = finalConnection.query(from(finalSql));

const valuesStream = new Readable({
  objectMode: true,
});

valuesStream
  .pipe(deparser())
  .pipe(copyFromStream);

valuesStream.push([
  {
    type: 'int4',
    value: 1,
  },
  {
    type: 'int4',
    value: 1,
  },
  {
    type: 'int4',
    value: 1,
  },
  {
    type: 'int4',
    value: 1,
  },
]);

valuesStream.push(null);

```

**Comment by gajus** [comment]
Works 👍 

FYI, I have added this module to Slonik.

https://github.com/gajus/slonik#slonik-query-methods-copyfrombinary

**Comment by jeromew** [comment]
great ! you should probably mention in the docs that not all types are implemented / maybe link to the library README - https://github.com/jeromew/node-pg-copy-streams-binary#currently-supported-types
